// Auto-generated config from .env
// Do not edit this file directly - it will be overwritten by build.js

window.MOMENTUM_CONFIG = {
  GOOGLE_CLIENT_ID: "551935422718-rl00vc7idsjjl26j3jcpdrd7norl7e9a.apps.googleusercontent.com",
  GOOGLE_REDIRECT_URI: "https://cgllcimklknkhkghnnablfjmebnaokdg.chromiumapp.org/",
  // Note: CLIENT_SECRET is not included for security (not needed in client-side extensions)
};

console.log("[Momentum] Configuration loaded");
